export const dummyData = {
  products: [
    {
      DeviceId: "IOTQ001",
      DeviceLocation: "Hyderabad_Madhapur",
      Voltage: 230.6,
      Current: 0.5,
      Power: 0.001,
      PowerFactor: 1.0,
      PumpStatus: "ON",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ002",
      DeviceLocation: "Bangalore_Whitefield",
      Voltage: 220.0,
      Current: 0.8,
      Power: 0.002,
      PowerFactor: 0.98,
      PumpStatus: "OFF",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ003",
      DeviceLocation: "Chennai_OMR",
      Voltage: 215.5,
      Current: 1.0,
      Power: 0.003,
      PowerFactor: 0.99,
      PumpStatus: "DEFECT",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ004",
      DeviceLocation: "Mumbai_Andheri",
      Voltage: 230.0,
      Current: 0.7,
      Power: 0.004,
      PowerFactor: 0.95,
      PumpStatus: "ON",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ005",
      DeviceLocation: "Delhi_Rohini",
      Voltage: 225.0,
      Current: 0.6,
      Power: 0.005,
      PowerFactor: 1.0,
      PumpStatus: "OFF",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ006",
      DeviceLocation: "Pune_Hinjewadi",
      Voltage: 240.0,
      Current: 0.5,
      Power: 0.006,
      PowerFactor: 0.97,
      PumpStatus: "DEFECT",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ007",
      DeviceLocation: "Kolkata_SaltLake",
      Voltage: 235.0,
      Current: 0.4,
      Power: 0.007,
      PowerFactor: 0.98,
      PumpStatus: "ON",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ008",
      DeviceLocation: "Hyderabad_BanjaraHills",
      Voltage: 228.0,
      Current: 0.3,
      Power: 0.008,
      PowerFactor: 0.96,
      PumpStatus: "OFF",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ009",
      DeviceLocation: "Bangalore_ElectronicsCity",
      Voltage: 220.0,
      Current: 0.2,
      Power: 0.009,
      PowerFactor: 0.99,
      PumpStatus: "DEFECT",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ010",
      DeviceLocation: "Chennai_AnnaNagar",
      Voltage: 210.0,
      Current: 0.1,
      Power: 0.01,
      PowerFactor: 1.0,
      PumpStatus: "ON",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ011",
      DeviceLocation: "Mumbai_Bandra",
      Voltage: 200.0,
      Current: 0.9,
      Power: 0.011,
      PowerFactor: 0.95,
      PumpStatus: "OFF",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ012",
      DeviceLocation: "Delhi_VasantKunj",
      Voltage: 195.0,
      Current: 0.8,
      Power: 0.012,
      PowerFactor: 0.96,
      PumpStatus: "DEFECT",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ013",
      DeviceLocation: "Pune_Kothrud",
      Voltage: 190.0,
      Current: 0.7,
      Power: 0.013,
      PowerFactor: 0.97,
      PumpStatus: "ON",
      DeviceType: "borewell",
    },
    {
      DeviceId: "IOTQ014",
      DeviceLocation: "Kolkata_ParkStreet",
      Voltage: 185.0,
      Current: 0.6,
      Power: 0.014,
      PowerFactor: 0.98,
      PumpStatus: "OFF",
      DeviceType: "borewell",
    },
  ],
  newOffset: 0,
  totalProducts: 20,
};
